[package]
name = "xi_glium"
version = "0.0.0"
authors = ["Pavel Potocek <pavelpotocek@gmail.com>"]
license = "MIT"

[dependencies]
clipboard = "*"
glib = "*"
glium = "0.14"
gtk = "*"
serde_json = "*"

[dependencies.glium_text]
path = "glium_text"
