[package]
name = "xi_glium"
version = "0.0.0"
authors = ["Pavel Potocek <pavelpotocek@gmail.com>"]
license = "MIT"

[dependencies]
clipboard = "0.1.2"
glib = "0.1.0"
glium = "0.14"
gtk = "0.0.7"
serde_json = "0.7.2"

[dependencies.glium_text]
path = "glium_text"
